# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src\assistant_gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(778, 374)
        MainWindow.setMinimumSize(QtCore.QSize(778, 374))
        MainWindow.setMaximumSize(QtCore.QSize(778, 374))
        MainWindow.setMouseTracking(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("src\\../voice-assistant.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setGeometry(QtCore.QRect(10, 120, 761, 201))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(10, 10, 111, 101))
        self.graphicsView.setObjectName("graphicsView")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 778, 26))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_2 = QtWidgets.QAction(MainWindow)
        self.action_2.setObjectName("action_2")
        self.action_3 = QtWidgets.QAction(MainWindow)
        self.action_3.setObjectName("action_3")
        self.action_4 = QtWidgets.QAction(MainWindow)
        self.action_4.setCheckable(True)
        self.action_4.setObjectName("action_4")
        self.action_5 = QtWidgets.QAction(MainWindow)
        self.action_5.setCheckable(True)
        self.action_5.setChecked(True)
        self.action_5.setObjectName("action_5")
        self.action_6 = QtWidgets.QAction(MainWindow)
        self.action_6.setCheckable(True)
        self.action_6.setObjectName("action_6")
        self.menu.addAction(self.action_5)
        self.menu.addAction(self.action_4)
        self.menu.addAction(self.action_6)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Голосовой помощник"))
        self.plainTextEdit.setPlainText(_translate("MainWindow", "Сначала было слово"))
        self.menu.setTitle(_translate("MainWindow", "Слушать"))
        self.action_2.setText(_translate("MainWindow", "Слушать активно"))
        self.action_3.setText(_translate("MainWindow", "Не слушать"))
        self.action_4.setText(_translate("MainWindow", "Активно"))
        self.action_4.setWhatsThis(_translate("MainWindow", "Помощник будет слушать всё, что сможет без остановок. "))
        self.action_5.setText(_translate("MainWindow", "Обычно (60 сек)"))
        self.action_5.setToolTip(_translate("MainWindow", "Засыпать через 60 сек"))
        self.action_5.setWhatsThis(_translate("MainWindow", "Если нет команд в течение 60 сек, помощник переходит в неактивный режим, выйти из которого можно только назвав его имя"))
        self.action_6.setText(_translate("MainWindow", "Только по имени"))
        self.action_6.setWhatsThis(_translate("MainWindow", "Режим, в котором помощник слушает команду только после своего имени"))
